<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Minesweeper_WPF</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Images\GameBoard\Screenshot\Covered.png" />
    <None Remove="hatter.png" />
    <Content Include="Assets\**\*.*">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Assets\App.xaml.cs" />
    <Compile Remove="Assets\WidthToMarginConverter.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Images\GameBoard\Screenshot\Covered.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="hatter.png" />
  </ItemGroup>

</Project>
